apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-job
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: kaniko-builder
      restartPolicy: Never
      containers:
        - name: kaniko
          image: gcr.io/kaniko-project/executor:v1.20.1
          args:
            - "--context=__CONTEXT_URL__"
            - "--destination=__IMAGE_DEST__"
            - "--snapshotMode=time"
            - "--skip-unused-stages=true"
          env:
            - name: DOCKER_CONFIG
              value: /kaniko/.docker
          volumeMounts:
            - name: docker-config
              mountPath: /kaniko/.docker
      volumes:
        - name: docker-config
          secret:
            secretName: dockerhub-creds
