{{- if .Values.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grocery-compare.fullname" . }}-secrets
type: Opaque
data:
{{- range $key, $value := .Values.secretEnv }}
{{- if $value }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
{{- end }}
