{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "grocery-compare.fullname" .) .Values.serviceAccount.name }}
  labels:
    app.kubernetes.io/name: {{ include "grocery-compare.name" . }}
    helm.sh/chart: {{ include "grocery-compare.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
